### ISSUE TITLE
it now costs 2^31 something gold to buy any of those improvements

### ISSUE THREAD

**Issue by ajustsomebody** [paontv/Difficulty_Sandbox#6]

**Comment by paontv** [comment]
The price is high so that AI will not buy it.

**Comment by ajustsomebody** [comment]
> The price is high so that AI will not buy it.

how will the player buy it though, it used to cost 0 gold to get it

**Comment by paontv** [comment]
> > The price is high so that AI will not buy it.
> 
> how will the player buy it though, it used to cost 0 gold to get it

You can do this by selecting the difficulty level in the Sandbox.
